### ISSUE TITLE
Carga de imagenes

### ISSUE THREAD

**Issue by RouryR** [RouryR/SC-403-DAWP_Grupo2#1]
La carga de imágenes en el HTML no está funcionando, he agregado rutas relativas y rutas absolutas y no funciona.
Hay que investigar más.

**Comment by Cerem0208** [comment]
> La carga de imágenes en el HTML no está funcionando, he agregado rutas relativas y rutas absolutas y no funciona. Hay que investigar más.

No permite al colocarlo con ruta, sin embargo, al colocar el URL de la imagen si se ve reflejada en el "localhost"

**Comment by Cerem0208** [comment]
issue closed:

faltaba formato de thymeleaf: @{} en el URL

**Comment by RouryR** [comment]
Issue resuelto!
